/* Signal Atelier: onboarding is a measured sequence — identity, environment, then first checkpoints. */
import { FormEvent, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronDown, Plus, Trash2, Workflow } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { clientApi, getApiError } from "@/api/client";

type NewFlow = { flowName: string; tests: string[] };
const emptyFlow = (): NewFlow => ({ flowName: "", tests: [""] });

export default function CreateClientPage() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ clientName: "", baseUrl: "", browser: "chrome", headless: true, siteUsername: "", sitePassword: "", timeoutSeconds: 10, retryCount: 1, runTimeoutMinutes: 10, notifyPolicy: "always", chatId: "" });
  const [flows, setFlows] = useState<NewFlow[]>([emptyFlow()]);
  const [saving, setSaving] = useState(false);
  const update = (field: string, value: unknown) => setForm((current) => ({ ...current, [field]: value }));
  function updateFlow(index: number, patch: Partial<NewFlow>) { setFlows((current) => current.map((flow, flowIndex) => flowIndex === index ? { ...flow, ...patch } : flow)); }
  function updateTest(flowIndex: number, testIndex: number, value: string) { setFlows((current) => current.map((flow, index) => index === flowIndex ? { ...flow, tests: flow.tests.map((test, childIndex) => childIndex === testIndex ? value : test) } : flow)); }
  async function submit(event: FormEvent) {
    event.preventDefault();
    if (!/^[a-z0-9-]+$/.test(form.clientName)) { toast.error("Client name must use lowercase letters, numbers, or hyphens."); return; }
    try { new URL(form.baseUrl); } catch { toast.error("Enter a valid base URL."); return; }
    const validFlows = flows.filter((flow) => flow.flowName.trim()).map((flow) => ({ flowName: flow.flowName.trim(), tests: flow.tests.map((test) => test.trim()).filter(Boolean) })).filter((flow) => flow.tests.length);
    setSaving(true);
    try { const response = await clientApi.create({ ...form, clientName: form.clientName.trim(), flows: validFlows.reduce<Record<string, { tests: string[] }>>((accumulator, flow) => { accumulator[flow.flowName] = { tests: flow.tests }; return accumulator; }, {}) }); toast.success("Client created", { description: response.data.message || "The environment is ready for configuration." }); navigate(`/clients/${response.data.clientId}`); } catch (error) { toast.error(getApiError(error)); } finally { setSaving(false); }
  }
  return <div className="content-stack narrow-content">
    <Link to="/clients" className="back-link"><ArrowLeft size={15} />Back to clients</Link>
    <section className="form-intro"><div className="eyebrow accent-eyebrow">NEW ENVIRONMENT / 01</div><h2>Register a client path.</h2><p>Give Assuredia the environment details it needs to run and report browser tests on your schedule.</p></section>
    <form onSubmit={submit} className="create-layout">
      <div className="form-panel"><div className="panel-heading"><div className="panel-icon"><Workflow size={18} /></div><div><h3>Client identity</h3><p>The name becomes the stable identifier across runs and webhooks.</p></div></div><div className="form-grid"><div className="field-wrap full"><label className="field-label" htmlFor="clientName">Client name <span>Required</span></label><input id="clientName" className="text-field" placeholder="acme-store" value={form.clientName} onChange={(event) => update("clientName", event.target.value.toLowerCase())} /><small>Lowercase letters, numbers, and hyphens only.</small></div><div className="field-wrap full"><label className="field-label" htmlFor="baseUrl">Base URL <span>Required</span></label><input id="baseUrl" className="text-field mono" placeholder="https://staging.acme.com" value={form.baseUrl} onChange={(event) => update("baseUrl", event.target.value)} /></div></div></div>
      <div className="form-panel"><div className="panel-heading"><div className="panel-icon blue"><ChevronDown size={18} /></div><div><h3>Runtime defaults</h3><p>These settings apply to immediate and scheduled runs unless overridden.</p></div></div><div className="form-grid"><div className="field-wrap"><label className="field-label" htmlFor="browser">Browser</label><select id="browser" className="select-field" value={form.browser} onChange={(event) => update("browser", event.target.value)}><option value="chrome">Chrome</option><option value="firefox">Firefox</option><option value="edge">Edge</option></select></div><div className="field-wrap"><label className="field-label" htmlFor="notifyPolicy">Notify policy</label><select id="notifyPolicy" className="select-field" value={form.notifyPolicy} onChange={(event) => update("notifyPolicy", event.target.value)}><option value="always">Always</option><option value="on_failure">On failure</option><option value="never">Never</option></select></div><NumberField id="timeoutSeconds" label="Timeout seconds" value={form.timeoutSeconds} onChange={(value) => update("timeoutSeconds", value)} /><NumberField id="retryCount" label="Retry count" value={form.retryCount} onChange={(value) => update("retryCount", value)} /><NumberField id="runTimeoutMinutes" label="Run timeout minutes" value={form.runTimeoutMinutes} onChange={(value) => update("runTimeoutMinutes", value)} /><div className="field-wrap toggle-wrap"><label className="field-label">Headless browser</label><button type="button" className={`toggle ${form.headless ? "on" : ""}`} onClick={() => update("headless", !form.headless)} aria-pressed={form.headless}><span /></button><small>{form.headless ? "Runs without a visible browser window." : "Runs with a visible browser window."}</small></div></div></div>
      <div className="form-panel"><div className="panel-heading"><div className="panel-icon green"><Check size={18} /></div><div><h3>Site access <span className="optional">Optional</span></h3><p>Credentials are sent to the existing backend and never displayed after saving.</p></div></div><div className="form-grid"><div className="field-wrap"><label className="field-label" htmlFor="siteUsername">Site username</label><input id="siteUsername" className="text-field" placeholder="qa-user" value={form.siteUsername} onChange={(event) => update("siteUsername", event.target.value)} /></div><div className="field-wrap"><label className="field-label" htmlFor="sitePassword">Site password</label><input id="sitePassword" type="password" className="text-field" placeholder="••••••••" value={form.sitePassword} onChange={(event) => update("sitePassword", event.target.value)} /></div><div className="field-wrap"><label className="field-label" htmlFor="chatId">Chat ID</label><input id="chatId" className="text-field" placeholder="123456" value={form.chatId} onChange={(event) => update("chatId", event.target.value)} /></div></div></div>
      <div className="form-panel"><div className="panel-heading"><div className="panel-icon amber"><Workflow size={18} /></div><div><h3>First flows <span className="optional">Optional</span></h3><p>Seed the first test checkpoints. You can edit them later from the client workspace.</p></div></div>{flows.map((flow, flowIndex) => <div className="flow-builder" key={flowIndex}><div className="flow-builder-head"><input className="text-field" placeholder="Flow name, e.g. login" value={flow.flowName} onChange={(event) => updateFlow(flowIndex, { flowName: event.target.value })} />{flows.length > 1 && <button type="button" className="danger-icon" onClick={() => setFlows((current) => current.filter((_, index) => index !== flowIndex))}><Trash2 size={15} /></button>}</div><div className="test-list">{flow.tests.map((test, testIndex) => <div className="test-row" key={testIndex}><span className="test-index">{String(testIndex + 1).padStart(2, "0")}</span><input className="text-field mono" placeholder="LoginTest.testLogin" value={test} onChange={(event) => updateTest(flowIndex, testIndex, event.target.value)} />{flow.tests.length > 1 && <button type="button" className="icon-button" onClick={() => updateFlow(flowIndex, { tests: flow.tests.filter((_, index) => index !== testIndex) })}><Trash2 size={14} /></button>}</div>)}<button type="button" className="add-test" onClick={() => updateFlow(flowIndex, { tests: [...flow.tests, ""] })}><Plus size={14} />Add test entry</button></div></div>)}<button type="button" className="secondary-button" onClick={() => setFlows((current) => [...current, emptyFlow()])}><Plus size={15} />Add another flow</button></div>
      <div className="form-actions"><Link className="secondary-button" to="/clients">Cancel</Link><button className="primary-button" type="submit" disabled={saving}>{saving ? "Creating client…" : "Create client"}<ArrowRight size={16} /></button></div>
    </form>
  </div>;
}

function NumberField({ id, label, value, onChange }: { id: string; label: string; value: number; onChange: (value: number) => void }) { return <div className="field-wrap"><label className="field-label" htmlFor={id}>{label}</label><input id={id} type="number" min="0" className="text-field mono" value={value} onChange={(event) => onChange(Number(event.target.value))} /></div>; }
